// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var anchura2_, anchuras_;
    $('#menu_gen li a').click(function(event) {
      var mothra, soursa, turno;
      event.preventDefault();
      $('#menu_gen li a').removeClass('active');
      $(this).addClass('active');
      $('#header').animate({
        top: 0,
        marginTop: 0
      }, 400);
      soursa = $(this).attr('href');
      mothra = $(window).height();
      turno = $(this).attr('rel');
      $('.upao').css('display', 'none');
      return $('#container').animate({
        marginTop: '-' + mothra * turno + 'px'
      }, 400, function() {
        $('#header').addClass('nona');
        return $('.lista_hi li img').each(function() {
          var altos_2;
          altos_2 = $(this).height();
          return $(this).css('margin-top', '-' + altos_2 * 0.5 + 'px');
        });
      });
    });
    anchuras_ = $(window).width();
    anchura2_ = anchuras_ - 400;
    if (anchuras_ >= 1000) {
      $('.activao').css('width', anchura2_);
    } else {
      $('.activao').css('width', '600px');
    }
    $(window).resize(function() {
      var anchura2, anchuras;
      anchuras = $(window).width();
      anchura2 = anchuras - 400;
      if (anchuras >= 1000) {
        return $('.activao').css('width', anchura2);
      } else {
        return $('.activao').css('width', '600px');
      }
    });
    $('a.upa').qtip({
      style: {
        name: 'dark',
        tip: true
      },
      position: {
        corner: {
          target: 'topMiddle',
          tooltip: 'bottomMiddle'
        }
      }
    });
    $('a.upao').qtip({
      style: {
        name: 'dark',
        tip: true
      },
      position: {
        corner: {
          target: 'bottomMiddle',
          tooltip: 'topMiddle'
        }
      }
    });
    return $('#launch').click(function(e) {
      var ancho, iteration;
      iteration = $(this).data('iteration') || 1;
      e.preventDefault();
      switch (iteration) {
        case 1:
          $(this).children().attr('src', 'images/cerrar.png');
          ancho = $(window).width() - 400;
          $(this).children('span').text('Menú');
          $(this).attr('title', 'Cerrar el Menú');
          $('#changes').animate({
            marginRight: '-250px'
          }, 400);
          $('#cont_in').addClass('activao');
          $('#cont_in').delay(410).animate({
            width: ancho
          }, 1000);
          break;
        case 2:
          $(this).children().attr('src', 'images/menu.png');
          $(this).children('span').text('Menú');
          $(this).attr('title', 'Abrir el Menú');
          $('#changes').delay(1010).animate({
            marginRight: '0px'
          }, 400);
          $('#cont_in').removeClass('activao');
          $('#cont_in').animate({
            width: 0
          }, 1000);
          break;
      }
      iteration++;
      if (iteration > 2) {
        iteration = 1;
      }
      return $(this).data('iteration', iteration);
    });
  });

}).call(this);
